version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: "./docker/source/nginx/prod/Dockerfile"
    volumes:
      - "./app/shop:/app"
      - "./docker/source/nginx/prod/conf.d:/etc/nginx/conf.d:ro"
      - "./docker/logs/prod:/var/log/nginx"
    expose:
      - "80"
    ports:
      - "${EXTERNAL_WEB_PROD_PORT}:80"
    env_file:
      - "./docker/env/prod/APP_ENV.env"
      - "./docker/env/prod/VIRTUAL_HOST.env"
  db:
    build:
      context: ./
      dockerfile: "./docker/source/mariadb/prod/Dockerfile"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/source/mariadb/db_dump/db_shop:/docker-entrypoint-initdb.d"
    env_file:
      - "./docker/env/prod/db.env"
  php:
    image: "${APP_NAME}-php-prod:${TAG}"
    build:
      context: ./
      dockerfile: "./docker/source/php/prod/Dockerfile"
    volumes:
      - "./app/shop:/app"
      - "./docker/source/php/prod/app/common/config:/app/environments/prod/common/config:rw"
    env_file:
      - "./docker/env/prod/APP_ENV.env"
  adminer:
    build:
      context: ./
      dockerfile: "./docker/source/adminer/Dockerfile"
    ports:
      - "${EXTERNAL_ADMINER_PROD_PORT}:80"
